apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: node-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: mydatabase
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 50386
