apiVersion: v1
kind: Service
metadata: 
  name: devops-service
  labels:
    app: devops
spec:
  type: NodePort  
  selector:
    app: devops
    tier: frontend
  ports:
    - port: 3000         # external service port
      targetPort: 3000   # container port
